adapter: lmstudio
model: qwen/qwen3-8b
model_name: qwen/qwen3-8b
is_simulation: false
dataset: evals_dataset.json
output: eval_scores_output_qwen3_8b.csv
output_dir: outputs
lmstudio_endpoint: http://127.0.0.1:1234/v1/chat/completions
temperature: 0.7
use_timestamp_output_dir: true
