adapter: openrouter
model: openai/gpt-oss-20b:free
model_name: openai/gpt-oss-20b:free
is_simulation: false
dataset: evals_dataset.json
output: eval_scores_output_openrouter_gpt_oss_20b_free.csv
output_dir: outputs
openrouter_api_key: ""  # Uses OPENROUTER_API_KEY from environment
openrouter_endpoint: https://openrouter.ai/api/v1/chat/completions
temperature: 0.7
use_timestamp_output_dir: true
collect_metrics: true
