adapter: lmstudio
model: openchat_3.5
model_name: openchat_3.5
is_simulation: false
dataset: evals_dataset.json
output: eval_scores_output_openchat_35.csv
output_dir: outputs
lmstudio_endpoint: http://127.0.0.1:1234/v1/chat/completions
temperature: 0.7
max_tokens: 1024
use_timestamp_output_dir: true
